In [38]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [39]:
credit_card_data = pd.read_csv(r"C:\Users\frien\Downloads\creditcard.csv")

In [40]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [41]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [42]:
credit_card_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [9]:
# checking missing values
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [43]:
# legit and fraud transaction
credit_card_data['Class'].value_counts()
# 1 -> fraud and 0 -> legit

Class
0    284315
1       492
Name: count, dtype: int64

In [44]:
# seprating data 
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [45]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [46]:
# statical measure for this data 
print(legit['Amount'].describe())
print()
print(fraud['Amount'].describe())

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [47]:
# comparing these values
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [48]:
legit_sample = legit.sample(n = 492)

In [49]:
# concatinating 2 dt frame
new_dt = pd.concat([legit_sample, fraud], axis = 0) # rowwise adding

In [50]:
new_dt.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
114149,73354.0,1.195603,0.514898,-0.295325,1.276265,0.084540,-0.762340,0.120528,-0.023135,0.135089,...,-0.041077,-0.083451,-0.072223,-0.074344,0.569328,-0.292992,0.038865,0.044718,1.00,0
242113,151344.0,1.830315,-0.896792,-0.587573,-0.351231,-0.751681,-0.160426,-0.707717,0.110003,0.943871,...,0.250578,0.560299,0.175109,0.843508,-0.548809,1.207576,-0.111330,-0.046113,96.79,0
115477,73885.0,-1.958193,1.786423,2.091884,1.482579,-0.301168,2.040365,-1.969555,-5.870413,0.781983,...,1.383055,-1.056794,0.017627,0.057440,-0.266383,-0.461574,-0.105620,-0.253671,33.49,0
157619,110149.0,1.972701,-0.200472,-0.161495,0.550266,-0.646760,-0.716656,-0.558036,-0.144319,2.656908,...,-0.260821,-0.395217,0.367159,-0.141997,-0.420191,-0.959582,0.031793,-0.032804,11.27,0
150542,93620.0,-1.429301,-1.085315,-0.261994,0.522977,4.076495,-1.255270,0.230149,-0.245216,0.389290,...,0.133362,0.089849,-0.054909,-0.280565,0.886091,-0.539896,-0.315896,-0.235507,29.80,0

In [51]:
new_dt.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,92836.638211,0.078237,-0.059210,0.059851,-0.104957,-0.049094,-0.081903,0.020090,-0.009194,-0.067901,...,0.007914,0.017182,0.028806,-0.051798,-0.011865,0.013506,-0.048900,0.017186,0.011810,100.521423
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [52]:
new_dt['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [53]:
# splitting data into featues and targets
x = new_dt.drop(columns = 'Class', axis = 1)
y = new_dt['Class']

In [56]:
x.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
114149,73354.0,1.195603,0.514898,-0.295325,1.276265,0.084540,-0.762340,0.120528,-0.023135,0.135089,...,-0.230584,-0.041077,-0.083451,-0.072223,-0.074344,0.569328,-0.292992,0.038865,0.044718,1.00
242113,151344.0,1.830315,-0.896792,-0.587573,-0.351231,-0.751681,-0.160426,-0.707717,0.110003,0.943871,...,0.042974,0.250578,0.560299,0.175109,0.843508,-0.548809,1.207576,-0.111330,-0.046113,96.79
115477,73885.0,-1.958193,1.786423,2.091884,1.482579,-0.301168,2.040365,-1.969555,-5.870413,0.781983,...,0.075019,1.383055,-1.056794,0.017627,0.057440,-0.266383,-0.461574,-0.105620,-0.253671,33.49
157619,110149.0,1.972701,-0.200472,-0.161495,0.550266,-0.646760,-0.716656,-0.558036,-0.144319,2.656908,...,-0.296434,-0.260821,-0.395217,0.367159,-0.141997,-0.420191,-0.959582,0.031793,-0.032804,11.27
150542,93620.0,-1.429301,-1.085315,-0.261994,0.522977,4.076495,-1.255270,0.230149,-0.245216,0.389290,...,0.499993,0.133362,0.089849,-0.054909,-0.280565,0.886091,-0.539896,-0.315896,-0.235507,29.80

In [57]:
y.head()

114149    0
242113    0
115477    0
157619    0
150542    0
Name: Class, dtype: int64

In [58]:
# spliting dt into taining and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify = y, random_state = 2)

In [59]:
print(x.shape, x_train.shape, x_test.shape)
print(y.shape, y_train.shape, y_test.shape)

(984, 30) (787, 30) (197, 30)
(984,) (787,) (197,)

In [60]:
# model training
model = LogisticRegression()

In [62]:
# training model with training data
model.fit(x_train, y_train)

C:\Users\frien\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [63]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [69]:
print('training data accuracy : ', training_data_accuracy)

training data accuracy :  0.9453621346886912

In [70]:
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [71]:
print('test data accuracy : ', test_data_accuracy)

test data accuracy :  0.9390862944162437